name: Build
on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  test:
    strategy:
      matrix:
        python-version:
          - "3.7"
          - "3.8"
          - "3.9"
          - "3.10"
        os:
          - macos
          - ubuntu

    name: tests
    runs-on: ${{ matrix.os }}-latest
    steps:
      - uses: actions/checkout@v3.0.2

      - uses: actions/setup-python@v4.2.0
        with:
          python-version: ${{ matrix.python-version }}

      - run: pip install .

      - name: run tests
        run: python setup.py test

  fuzz:
    name: fuzz
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.2

      - uses: actions/setup-python@v4.2.0
        with:
          python-version: "3.10"

      - run: pip install .

      - name: run fuzz
        run: python test_fuzz.py ./*.py
